title: Jesse Dillman
email: jesse@jdillman.com
baseurl: ""
url: ""
markdown: kramdown
permalink: /blog/:title/
paginate_path: "/page/:num/"
sass:
  sass_dir: _sass
paginate: 5
plugins: [jekyll-paginate, jekyll-archives]
collections:
- work
jekyll-archives:
  enabled: [categories]
  layout: 'archive'
  permalinks:
    category: '/category/:name/'
algolia:
  application_id: 'Y2N7OVVUWU'
  index_name: 'jdillman'
  nodes_to_index: 'p,blockquote,li,h2,h3'
exclude: [netlify.toml]